name: Monthly Web Scraper

on:
  schedule:
    - cron: '0 17 1 * *'  # 5PM UTC on the 1st of every month
  workflow_dispatch:      # Optional: allows manual triggering from GitHub UI

jobs:
  run-scraper:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v3
  
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Download spaCy model
      run: python -m spacy download en_core_web_sm
    
    - name: Run scraper
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DB: brand_monitoring
          RAW_COLLECTION: raw_articles
          SPLASH_URL: ${{ secrets.SPLASH_URL }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          SMTP_SERVER: smtp.gmail.com
          SMTP_PORT: 587
        run: python WebScraper.py
